name: Build ShimaStyle Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Cho phép kích hoạt build thủ công từ giao diện GitHub

env:
  THEOS: ${{ github.workspace }}/theos

jobs:
  build:
    name: Build .deb Package
    runs-on: macos-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: brew install ldid xz

      - name: Setup Theos & iOS SDKs
        run: |
          # Tải Theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          # Tải iOS SDKs (giải nén trực tiếp để tiết kiệm thời gian)
          curl -sL https://github.com/theos/sdks/archive/master.tar.gz | tar -x -z -C $THEOS/sdks --strip-components=1

      - name: Build Tweak (Make Package)
        run: make package FINALPACKAGE=1

      - name: Upload .deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShimaStyle-Package
          path: packages/*.deb